### ISSUE TITLE
Security: check the response

### ISSUE THREAD

**Issue by frspp** [Spot-hinta-fi/Shelly#16]
`Shelly.call("HTTP.GET", { url: urlToCall, timeout: 15, ssl_ca: "*" }, RunResponse);`

`function RunResponse(result) {`

I guess the script should check the response so it accepts only integer number (the hour/rank or such) OR force the response to be an integer number, yes? Currently it seems to trust the response 'blindly', which is huge security flaw?

**Comment by Spot-hinta-fi** [comment]
These scripts do not read anything from the response body.  Only HTTP status code is read and action done based on that.  Otherwise I agree that response content should always be checked.

HTTP status is returned in response body by the API as well, but it is not read by the script at all.

Based on this, do you think this could be closed or should this be investigated more?
