### ISSUE TITLE
FR: Persentiili

### ISSUE THREAD

**Issue by frspp** [Spot-hinta-fi/Shelly#60]
Feature request:
_API voisi ilmoittaa Rank:in lisäksi myös persentiilin (kuinka suuri osa hinnoista on yhtä suuria tai pienempiä kuin kyseinen hinta).

Jos haluaisi lämmittää puolet vuorokaudesta, niin ehto "currentPrice.Percentile <= 50" hoitaisi homman. Vastaava Rank:ia käyttävä ehto on "currentPrice.Rank <= 12".

Tuota persentiiliä voisi käyttää, oli hinnat ilmoitettu sitten tunnin tai vartin jaksoille.

Vartin jaksoja on vuorokaudessa 96 kpl, joten "persentiili" kääntyy arkikielessä melkein suoraan jaksojen lukumääräksi._
source: https://lampopumput.info/foorumi/threads/spot-hinta-fi-yksinkertainen-p%C3%B6rssiohjaus-api-ja-sit%C3%A4-k%C3%A4ytt%C3%A4v%C3%A4t-automaatioskriptit.33938/page-36

**Comment by Spot-hinta-fi** [comment]
This would be quite good idea. However, the current idea related to coming 15mins pricing is that current scripts and API's work the same as today... i.e. hourly average price is calculated and then there is 24 "ranks" still.  This is because there are thousands of users.

New API's and scripts that will utilize 15 minutes prices are on planning board.  The challenge is that many devices really don't like that you change the status every 15 minutes in the worst case.
